schletter/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('schletter_app.urls', namespace='schletter_app')),
    ]+ static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

schletter_app/urls.py
"""URLs for schletter_app"""
from django.urls import path
from . import views
from .views import about_view

app_name = 'schletter_app'

urlpatterns = [
    # Home page
    path('', views.Index.as_view(), name='index'),
    # About page
    path('about/', about_view, name  = 'about'),

    # Calendar page
    path('calendar/', views.DateList.as_view(), name='calendar'),
    # Events
    path('events/', views.EventList.as_view(), name='events'),
    path('events/<int:pk>/', views.EventDetail.as_view(), name='event'),
    path('events/edit/<int:pk>/', views.EventEdit.as_view(), name='event_edit'),
    # Works
    path('works/', views.WorkList.as_view(), name="works"),
    path('works/<int:pk>', views.WorkDetail.as_view(), name='work'),
    path('works/edit/<int:pk>/', views.WorkEdit.as_view(), name='work_edit'),
    # Authors
    path('authors/', views.AuthorList.as_view(), name='authors'),
    path('authors/<int:pk>/', views.AuthorDetail.as_view(), name='author'),
    path('authors/edit/<int:pk>/', views.AuthorEdit.as_view(), name='author_edit'),

    # Composers
    path('composers/', views.ComposerList.as_view(), name='composers'),
    path('composers/<int:pk>/', views.ComposerDetail.as_view(), name='composer'),
    path('composers/edit/<int:pk>/', views.ComposerEdit.as_view(), name='composer_edit'),
]

schletter_app/models.py
from django.db import models
from django.urls import reverse
from datetime import datetime
from ckeditor.fields import RichTextField

# Create your models here.
class About(models.Model):
    """Schletter About page"""
    content = RichTextField(null=True, blank=True)

    class Meta:
        verbose_name_plural = 'About'

class Date(models.Model):
    date = models.DateField(primary_key=True)

    def __str__(self):
        date = self.date.strftime('%a, %-d %b %Y')
        return date

class Event(models.Model):
    """Schletter Event model"""
    date  = models.ForeignKey(Date, on_delete=models.CASCADE)
    event_order = models.PositiveSmallIntegerField(
        default = 0, blank = False, null = False, db_index = True,
    )
    title = models.CharField(max_length=100)
    theater = models.CharField(max_length=3)
    company = models.CharField(max_length=10)
    event_type = models.CharField(max_length=50)
    hadamowsky = models.CharField(max_length=5)
    morrow = models.CharField(max_length=5)
    notes = RichTextField(null=True, blank=True)
    
    def __str__(self):
        event = str(self.date) + ", " + self.title
        return event

    def get_absolute_url(self):
        return reverse('schletter_app:event', kwargs={'pk': self.pk})
        
    class Meta:
        ordering = ['event_order']
    
class Work(models.Model):
    events = models.ManyToManyField(Event, through="WorkEvent")
    title = models.CharField(max_length=100)
    source_title = models.CharField(max_length=100, null=True, blank=True)
    sort_title = models.CharField(max_length=100, null=True)
    genre = models.CharField(max_length=75)
    source_genre = models.CharField(max_length=75, null=True, blank=True)
    notes = RichTextField(null=True, blank=True)
    title_page = models.ImageField(null=True, blank=True, upload_to="images/")
    url = models.URLField(max_length=200, null=True, blank=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('schletter_app:work', kwargs={'pk': self.pk})
    
    class Meta:
        ordering = ['sort_title']

class WorkEvent(models.Model):
    id = models.IntegerField(primary_key=True)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.event.date) + ", " + self.event.title 
    
    class Meta:
        ordering = ['event__event_order',]

class Author(models.Model):
    works = models.ManyToManyField(Work, through="AuthorWork", related_name="authorworks")
    last_name = models.CharField(max_length=100)
    first_names = models.CharField(max_length=200)
    birth = models.IntegerField()
    death = models.IntegerField()
    notes = RichTextField(null=True, blank=True)

    def __str__(self):
        if self.first_names == "NA":
            return self.last_name
        else:
            return self.last_name + ", " + self.first_names

    def get_absolute_url(self):
        return reverse('schletter_app:author', kwargs={'pk': self.pk})
    
    class Meta:
        ordering = ['last_name', 'first_names']

class AuthorWork(models.Model):
    id = models.IntegerField(primary_key=True)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    role = models.CharField(max_length=100)

    def __str__(self):
        return self.author.last_name + ", " + self.work.title
    
    class Meta:
        ordering = ['author__last_name',]
    

class Composer(models.Model):
    works = models.ManyToManyField(Work, through="ComposerWork",related_name="composerworks")
    last_name = models.CharField(max_length=100)
    first_names = models.CharField(max_length=200)
    birth = models.IntegerField()
    death = models.IntegerField()
    notes = RichTextField(null=True, blank=True)

    def __str__(self):
        if self.first_names == "NA":
            return self.last_name
        else:
            return self.last_name + ", " + self.first_names

    def get_absolute_url(self):
        return reverse('schletter_app:composer', kwargs={'pk': self.pk})
    
    class Meta:
        ordering = ['last_name', 'first_names']

class ComposerWork(models.Model):
    id = models.IntegerField(primary_key=True)
    composer = models.ForeignKey(Composer, on_delete=models.CASCADE)
    work = models.ForeignKey(Work, on_delete=models.CASCADE)
    role = models.CharField(max_length=100)

    def __str__(self):
        return self.composer.last_name + ", " + self.work.title
    
    class Meta:
        ordering = ['composer__last_name',]

schletter_app/forms.py
from django import forms
from .models import Event, Work, Author, Composer 
from ckeditor.widgets import CKEditorWidget

class EventForm(forms.ModelForm):
    notes = forms.CharField(widget=CKEditorWidget(), required=False)

    class Meta:
        model = Event
        fields = ['theater', 'company', 'title', 'notes']
        THEATER_CHOICES = (
            ('Bth', 'Bth'),
            ('Kth', 'Kth')
        )
        COMPANY_CHOICES = (
            ('Court', 'Court'),
            ('French', 'French'),
            ('Jahn', 'Jahn'),
            ('Kinder', 'Kinder'),
            ('Preßburg', 'Preßburg'),
            ('unknown', 'unknown'),
        )
        widgets = {
            'theater': forms.Select(choices=THEATER_CHOICES, attrs={'class': 'form-control'}),
            'company': forms.Select(choices=COMPANY_CHOICES, attrs={'class': 'form-control'}),
            'title': forms.TextInput(attrs={'class': 'form-control'}),
        }

class WorkForm(forms.ModelForm):
    notes = forms.CharField(widget=CKEditorWidget(), required=False)

    class Meta:
        model = Work
        fields = ['title', 'notes', 'url', 'title_page']
        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'url': forms.URLInput(attrs={'class': 'form-control'}),
            'title_page': forms.ClearableFileInput(),
        }

class AuthorForm(forms.ModelForm):
    notes = forms.CharField(widget=CKEditorWidget(), required=False)

    class Meta:
        model = Author
        fields = ['birth', 'death', 'notes']
        widgets = {
            'birth': forms.NumberInput(attrs={'class': 'form-control'}),
            'death': forms.NumberInput(attrs={'class': 'form-control'}),
        }

class ComposerForm(forms.ModelForm):
    notes = forms.CharField(widget=CKEditorWidget(), required=False)

    class Meta:
        model = Composer
        fields = ['birth', 'death', 'notes']
        widgets = {
            'birth': forms.NumberInput(attrs={'class': 'form-control'}),
            'death': forms.NumberInput(attrs={'class': 'form-control'}),
        }

schletter_app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView, ListView, DetailView, UpdateView
from django.db.models import Q
from .models import About, Date, Event, Work, Author, Composer
from .forms import AuthorForm, ComposerForm, WorkForm, EventForm

# Create your views here.
class Index(TemplateView):
    """schletter_app home page """
    context_object_name = 'index'
    template_name = 'schletter_app/index.html'

# About
def about_view(request):
    context = {}
    context['about'] = About.objects.first()
    
    return render(request, "schletter_app/about.html", context)  

# Calendar
class DateList(ListView):
    context_object_name = 'calendar'
    model = Date
    paginate_by = 40
    template_name = 'schletter_app/calendar.html'
    
    def get_queryset(self):
        date_min = self.request.GET.get('date_min')
        date_max = self.request.GET.get('date_max')
        if date_min is not None and date_max is not None:
            return Date.objects.all().filter(date__gte=date_min, date__lte=date_max)
        else:
            return Date.objects.all()
    
# Events
class EventQueryMixin:
    def get_queryset(self):
        qs = Event.objects.all()
        theater = self.request.GET.get('theater')
        company = self.request.GET.getlist('company')
        event_type = self.request.GET.getlist('event_type')
        genre = self.request.GET.getlist('genre')
        if theater:
            qs = qs.filter(theater=theater)
        if company:
            qs = qs.filter(Q(company__in=company))
        if event_type:
            qs = qs.filter(Q(event_type__in=event_type))
        if genre:
            qs = qs.filter(Q(work__genre__in=genre) |
                           Q(work__source_genre__in=genre))
        return qs

class EventList(EventQueryMixin, ListView):
    context_object_name = 'events'
    paginate_by = 50
    template_name = 'schletter_app/events.html'
    # Value lists for drop downs in Event search
    extra_context = {
        'companies': Event.objects.all().exclude(company='NA').order_by('company').values_list('company', flat=True).distinct(),
        'event_types': Event.objects.all().order_by('event_type').values_list('event_type', flat=True).distinct(),
        'genres': Work.objects.all().order_by('genre').values_list('genre', flat=True).distinct()
        }

class EventDetail(EventQueryMixin, DetailView):
    context_object_name = 'event'
    model = Event
    template_name = 'schletter_app/event.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        prev_event = (
            self.get_queryset()
            .filter(event_order__lt=self.object.event_order)
            .reverse().values('pk')[:1]
        )
        # There may be no previous page
        if prev_event:
            context['prev_event'] = prev_event[0]['pk']
        
        next_event = (
            self.get_queryset()
            .filter(event_order__gt=self.object.event_order)
            .values('pk')[:1]
        )
        # There may be no next page
        if next_event:
            context['next_event'] = next_event[0]['pk']
        
        return context

class EventEdit(UpdateView):
    model = Event
    template_name = 'schletter_app/event_edit.html'
    form_class = EventForm


# Works
class WorkQueryMixin:
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is not None:
            return Work.objects.filter(Q(title__unaccent__icontains=query) | 
                    Q(source_title__unaccent__icontains=query) | 
                    Q(genre__unaccent__icontains=query) |
                    Q(source_genre__unaccent__icontains=query))   
        else:
            return Work.objects.all()

class WorkList(WorkQueryMixin, ListView):
    context_object_name = 'works'
    model = Work
    paginate_by = 50
    template_name = 'schletter_app/works.html'

class WorkDetail(WorkQueryMixin, DetailView):
    context_object_name = 'work'
    model = Work
    template_name = 'schletter_app/work.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        prev_pk = (
            self.get_queryset()
            .filter(sort_title__lt=self.object.sort_title)
            .reverse().values('pk')[:1]
        )
        # There may be no previous page
        if prev_pk:
            context['prev_pk'] = prev_pk[0]['pk']
        
        next_pk = (
            self.get_queryset()
            .filter(sort_title__gt=self.object.sort_title).values('pk')[:1]
        )
        # There may be no next page
        if next_pk:
            context['next_pk'] = next_pk[0]['pk']
        
        return context

class WorkEdit(UpdateView):
    model = Work
    template_name = 'schletter_app/work_edit.html'
    form_class = WorkForm

# Authors
class AuthorQueryMixin:
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is not None:
            return Author.objects.filter(Q(last_name__unaccent__icontains=query) | Q(first_names__unaccent__icontains=query) | Q(authorwork__role__icontains=query)).distinct()
        else:
            return Author.objects.all()

class AuthorList(AuthorQueryMixin, ListView):
    context_object_name = 'authors'
    model = Author
    paginate_by = 50
    template_name = 'schletter_app/authors.html'

class AuthorDetail(AuthorQueryMixin, DetailView):
    context_object_name = 'author'
    model = Author
    template_name = 'schletter_app/author.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        prev_pk = (
            self.get_queryset()
            .filter(last_name__lt=self.object.last_name)
            .reverse().values('pk')[:1]
        )
        # There may be no previous page
        if prev_pk:
            context['prev_pk'] = prev_pk[0]['pk']
        
        next_pk = (
            self.get_queryset()
            .filter(last_name__gt=self.object.last_name)
            .values('pk')[:1]
        )
        # There may be no next page
        if next_pk:
            context['next_pk'] = next_pk[0]['pk']
        
        return context

class AuthorEdit(UpdateView):
    model = Author
    form_class = AuthorForm
    template_name = 'schletter_app/author_edit.html'

# Composers
class ComposerQueryMixin:
    def get_queryset(self):
        query = self.request.GET.get('q')
        if query is not None:
            return Composer.objects.exclude(last_name="NA").filter(Q(last_name__unaccent__icontains=query) | Q(first_names__unaccent__icontains=query))
        else:
            return Composer.objects.all().exclude(last_name="NA")

class ComposerList(ComposerQueryMixin, ListView):
    context_object_name = 'composers'
    model = Composer
    paginate_by = 50
    template_name = 'schletter_app/composers.html'

class ComposerDetail(ComposerQueryMixin, DetailView):
    context_object_name = 'composer'
    model = Composer
    template_name = 'schletter_app/composer.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        prev_pk = (
            self.get_queryset()
            .filter(last_name__lt=self.object.last_name)
            .reverse().values('pk')[:1]
        )
        # There may be no previous page
        if prev_pk:
            context['prev_pk'] = prev_pk[0]['pk']
        
        next_pk = (
            self.get_queryset()
            .filter(last_name__gt=self.object.last_name)
            .values('pk')[:1]
        )
        # There may be no next page
        if next_pk:
            context['next_pk'] = next_pk[0]['pk']
        
        return context

class ComposerEdit(UpdateView):
    model = Composer
    form_class = ComposerForm
    template_name = 'schletter_app/composer_edit.html'

schletter_app/templates/schletter_app/about.html
{% extends 'schletter_app/base.html' %}
{% load my_tags %}
{% block page_title %}About{% endblock page_title %}
{% block page_header %}
  <h3 class="pb-2">About</h3>
{% endblock page_header %}

{% block content %}
    <div class="row col-sm-10">
        <div class="indent">
        {{ about.content | safe}}
        </div>
    </div>
{% endblock content %}

schletter_app/templates/schletter_app/author.html
{% extends 'schletter_app/base.html' %}
{% load my_tags %}
{% block page_title %}{{author.last_name}}{% endblock page_title %}
{% block page_header %}
  <h3 class="pb-2">{{author}}</h3>
{% endblock page_header %}

{% block content %}
  {% if author.birth > 0 %}<p>Birth: {{ author.birth }}</p>{% endif %}
  {% if author.death > 0 %}<p>Death: {{ author.death }}</p>{% endif %}
  <p>Work(s):</p>
  <ul>
    {% for aw in author.authorwork_set.all|sort_by:"work" %}
      <li>
        {% if aw.work.title == "No title" %}
          <a href="{% url 'schletter_app:work' aw.work.pk %}">
              {{aw.work.title}}</a>{% if aw.role != "NA" %} ({{aw.role}}){% endif %} 
        {% else %}
          <a href="{% url 'schletter_app:work' aw.work.pk %}">
              <em>{{aw.work.title}}</em></a>{% if aw.role != "NA" %} ({{aw.role}}){% endif %}{% if aw.work.source_title %}; original title: <em>{{aw.work.source_title}}</em>{% endif %}
        {% endif %}
      </li>
    {% endfor %}
  </ul>
  <p>Total: {{author.works.all.count}}</p>
  {% if author.notes != "NA" and author.notes != "<p>NA</p>"%}
    <p>Notes: </p>
    <div class="row col-sm-8">
      <div class="indent">{{ author.notes|safe }}</div>
    </div>
  {% endif %}
  {% if user.is_authenticated %}
    <a class="btn btn-outline-secondary btn-sm mt-2" href="{% url 'schletter_app:author_edit' author.pk %}">Edit</a>
  {% endif %}

  <!-- Previous and Next arrows -->
  <div class="arrow" id="arrow-left">
    {% if prev_pk %}
      <a href="{% url 'schletter_app:author' prev_pk %}?{{ request.GET.urlencode }}"><i class="bi-chevron-left"></i></a>
    {% endif %}
   </div> 
   <div class="arrow" id="arrow-right">
    {% if next_pk %}
      <a href="{% url 'schletter_app:author' next_pk %}?{{ request.GET.urlencode }}"><i class="bi-chevron-right"></i></a>
    {% endif %}
  </div>
{% endblock content %}

schletter_app/templates/schletter_app/authors.html
{% extends 'schletter_app/base.html' %}
{% block page_title %}Authors{% endblock page_title %}
{% block page_header %}
  <div class="row">
    <h2>Authors &#38; Choreographers</h2>
    <!-- paginator.count = number of items in current queryset -->
    <span class="pt-2 pl-2"> ({{ paginator.count }})</span>
  </div>
  <div class="row pb-3">
    <div class="pb-1 mt-2">Click on a row to see the detail view for the person</div> 
    <form class="form-inline ml-auto" action="{% url 'schletter_app:authors' %}" method="get">
      <div class="form-group pb-1 mr-2">
        <input name="q" class="form-control" type="text" placeholder="Search">
      </div>
      <div class="form-group pb-1 mr-2">
        <button class="btn btn-primary mr-2" type="submit">Search</button>
        <a class="btn btn-secondary mr-2" href="{% url 'schletter_app:authors' %}" role="button">Reset</a>
        <i class="mr-2 text-secondary bi-question-circle" style="font-size:24px" data-container="body" data-toggle="popover" data-placement="top" data-content="Case-insensitive search on  full or partial last or first names">
        </i>
      </div>
    </form>
  </div>
{% endblock page_header %}
{% block content %}
  {% for author in authors %}
    <a href="{{ author.get_absolute_url }}?{{ request.GET.urlencode }}" class="list-group-item list-group-item-action">
      {{ author }}            
    </a>
  {% empty %}
    <p>No authors match this search</p>
  {% endfor %}
{% endblock content %}

schletter_app/templates/schletter_app/base.html
{% load bootstrap4 %}
{% load my_tags %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>{% block page_title %}{% endblock  %}</title>
  <link rel="shortcut icon" type="image/png" href="{% static 'schletter/images/favicon.ico' %}">
  {% bootstrap_css %}
  {% bootstrap_javascript jquery='full' %}
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
  <link rel="stylesheet" href="{% static 'schletter/style.css' %}">
</head>
<!-- BODY -->
<body>
  <!-- Navbar -->
  <nav class="navbar sticky-top navbar-expand-md navbar-light bg-light mb-4 border">
    <a href="{% url 'schletter_app:index' %}" class="navbar-brand">Schletter</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span></button>
   
    <div class="collapse navbar-collapse" id="navbarCollapse">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schletter_app:calendar' %}">Calendar</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schletter_app:events' %}" >Events</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schletter_app:works' %}">Works</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schletter_app:authors' %}">Authors</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schletter_app:composers' %}">Composers</a>
        </li> 
      </ul> 
      <ul class="navbar-nav ml-auto">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'schletter_app:about' %} ">About</a>
        </li> 
      {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'logout' %}">Logout</a>
        </li>
        <li>
          <a class="nav-link" href="/admin">admin</a>
        </li>
      {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'login' %}?next={{request.path}}">Login</a>
        </li>
      {% endif %}    
      </ul>    
    </div>
  </nav>

  <!-- Content and pagination -->
  <main class="container">
    <div>
      {% block page_header %}{% endblock page_header %}
    </div>
    <div>
      {% block content %}{% endblock content %}
    </div>

    <!-- Bootstrap 4 pagination -->
    <!-- Adapted from https://www.caktusgroup.com/blog/2018/10/18/filtering-and-pagination-django/ -->
    {% if is_paginated %}
      <nav aria-label="Page navigation">
        <ul class="pagination pagination-sm justify-content-center">
          {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?{% param_replace page=1 %}">&laquo;</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="#"><span>&laquo;</span></a></li>
          {% endif %}
          {% for i in paginator.page_range %}
            {% if page_obj.number == i %}
              <li class="page-item active"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
            {% else %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
            {% endif %}
          {% endfor %}
          {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?{% param_replace page=page_obj.paginator.num_pages %}">&raquo;</a></li>
          {% else %}
            <li class="page-item disabled"><a class="page-link" href="#"><span>&raquo;</span></a></li>
          {% endif %}
        </ul>
      </nav>
    {% endif %}
  </main>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
  <script>
    $(function () {
      $('[data-toggle="popover"]').popover()
    })
  </script>
</body>
</html>

schletter_app/templates/schletter_app/event.html
{% extends 'schletter_app/base.html' %}
{% load my_tags %}
{% block page_title %}Event{% endblock page_title %}
{% block page_header %}
  <h3 class="pb-2">Event: {{event.date}}</h3>
{% endblock page_header %}

{% block content %}
  <p>Theater: {{ event.theater }}</p>
  <p>Company: {{ event.company }}</p>
  <p>Title: 
    {% with event.work_set.all.first as work %}
    {% if not work or event.event_type == "closed" %}
      <td>{{event.title}}</td>
    {% else %}
      <td><a href="{{ work.get_absolute_url }}">{{ event.title | display_title:work.genre | safe }}</a></td>
    {% endif %}
  </p>
  <p>Type: {{ event.event_type }}</p>
  <p>Genre: 
    {% if event.title != work.source_title %}
      {{ work.genre }}
    {% else %}
      {{work.source_genre}}
    {% endif %}
  </p>
    {% endwith %}
  {% if event.work_set.first.authorworks.exists %}
  <p>Author(s): </p>
    <ul>
      {% if event.company == "French" %}
        {% with event.work_set.first.authorwork_set.first as aw %}
          <li><a href="{% url 'schletter_app:author' aw.author.pk %}">{{ aw.author}}</a> ({{aw.role}})</li>
        {% endwith %}
      {% else %}
        {% for aw in event.work_set.first.authorwork_set.all %}
          <li><a href="{% url 'schletter_app:author' aw.author.pk %}">{{ aw.author}}</a>{% if aw.role != "NA" %} ({{aw.role}}){% endif %}</li>
        {% endfor %}
      {% endif %}
    </ul>
  {% endif %}
  {% if event.work_set.first.composerworks.exists and event.work_set.first.composerworks.first.last_name != "NA" %}
    <p>Composer: <a href="{% url 'schletter_app:composer' event.work_set.first.composerworks.first.pk %}">{{ event.work_set.first.composerworks.first }}</a></p>
  {% endif %}
  <p>Hadamowsky: {{event.hadamowsky}}</p>
  {% if event.morrow != "NA" %}
    <p>Morrow: {{event.morrow}}</p>
  {% endif %}
  {% if event.notes != "NA" and event.notes != "" %}
    <p>Notes: </p>
    <div class="row col-sm-8">
      <div class="indent">{{ event.notes|safe }}
      </div>
    </div>
  {% endif %}
  {% if user.is_authenticated %}
     <br> 
    <a class="btn btn-outline-secondary btn-sm mt-2" href="{% url 'schletter_app:event_edit' event.pk %}">Edit</a>
  {% endif %}
  <hr>
  <div style="font-size:16px"> 
    <p>All events in the theaters on {{event.date}}:</p>
    <ul>
      {% for event in event.date.event_set.all %}
        <li>
          {% with event.work_set.all.first as work %}
            {% if not work or event.event_type == "closed" %}
              <td>{{event.title}}</td>
            {% else %}
              <td><a href="{{ work.get_absolute_url }}">{{ event.title | display_title:work.genre | safe }}</a> ({{event.theater}}, {{work.genre}})</td>
            {% endif %}
          {% endwith %}
        </li>
      {% endfor %}
    </ul>
  </div>

  <!-- Previous and Next arrows -->
  <div class="arrow" id="arrow-left">
    {% if prev_event %}
      <a href="{% url 'schletter_app:event' prev_event %}?{{ request.GET.urlencode }}"><i class="bi-chevron-left"></i></a>
    {% endif %}
  </div>
  <div class="arrow" id="arrow-right">
    {% if next_event %}
      <a href="{% url 'schletter_app:event' next_event %}?{{ request.GET.urlencode }}"><i class="bi-chevron-right"></i></a>
    {% endif %}
  </div>
{% endblock content %}

schletter_app/templates/schletter_app/index.html
{% extends 'schletter_app/base.html' %}
{% block page_title %}Schletter{% endblock page_title %}
{% block content %}
  
  <script>
    $('body').addClass('home')
  </script>
  
  <div class="jumbotron text-center">
    <h2 class="pb-1">The Kärntnertortheater and the Burgtheater<br>1781–1782</h2>
    <h4 class="pb-4">The calendars of Salomo Friedrich Schletter</h4>
    <h5>David Black &#38; Dexter Edge</h5>
  </div>
{% endblock content %}